---
- name: Install and configure Nginx and Lighthouse
  become: true
  ansible.builtin.include_tasks:
    - install.yml
    - configure.yml

- name: Print address to connect
  ansible.builtin.debug:
    msg: "Lighthouse is available at http://{{ ansible_host }}:{{ lighthouse_http_port }}/"
